GET http://localhost:3001/api/persons

###
POST https://aged-glade-1903.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Pavlo",
    "phone": "555-44-33"
}

###
DELETE https://aged-glade-1903.fly.dev/api/persons/1