GET http://localhost:3001/api/persons

###
POST https://aged-glade-1903.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Pavlo",
    "phone": "555-44-33"
}

###
PUT http://localhost:3001/api/persons/6346256a73da1aa82f9c9474
Content-Type: application/json

{
    "name": "Pavlo",
    "phone": "000-00-00"
}

###
DELETE https://aged-glade-1903.fly.dev/api/persons/1